import type { Metadata } from "next";
import { inter } from "./fonts";
import "./globals.css";
import LenisWrapper from "@components/LenisWrapper";
import Footer from "@/components/footer/Footer";
import MenuHeader from "@/components/MenuHeader";
import ParallaxWrapper from "@/components/ParallaxWrapper";
import MobileHeader from "@/components/MobileHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <title>Charted Group - Luxury Trips</title>
        <meta charSet="utf-8"></meta>
        <meta property="og:title" content="Charted Group"></meta>

        <meta property="og:site_name" content="Charted Group"></meta>
        <meta
          name="description"
          content="Charted Group. Get your quote now. ✆ +353000 "
        ></meta>
        <meta property="og:description" content=""></meta>
        <meta property="og:locale" content="en"></meta>
        <meta name="robots" content="index, follow, nocache"></meta>
        <meta name="googlebot" content="index, follow, nocache"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        ></meta>
      </head>
      <body>
        <LenisWrapper>
          <ParallaxWrapper>
            <MenuHeader />
            {children}
          </ParallaxWrapper>
          {/* <Footer /> */}
        </LenisWrapper>
      </body>
    </html>
  );
}
